import React, { useState, useEffect } from "react";
import { 
  TrendingDown, 
  AlertTriangle, 
  Sparkles, 
  CheckCircle2, 
  ChevronRight, 
  RefreshCw, 
  ShoppingCart, 
  Package,
  Calendar
} from "lucide-react";
import { RestockPrediction, InventoryLot } from "../types";

interface DashboardProps {
  token: string;
  onNavigate: (tab: string) => void;
  triggerToast: (msg: string, type: "success" | "error") => void;
  listsCount: number;
  triggerSync: () => void;
}

export default function Dashboard({ token, onNavigate, triggerToast, listsCount, triggerSync }: DashboardProps) {
  const [stats, setStats] = useState({
    totalUniqueItems: 0,
    activeLotsCount: 0,
    expiringSoonCount: 0,
    expiredCount: 0,
    lowStockAlarmCount: 0,
    shoppingListItemsCount: 0
  });

  const [lots, setLots] = useState<InventoryLot[]>([]);
  const [predictions, setPredictions] = useState<RestockPrediction[]>([]);
  const [loadingStats, setLoadingStats] = useState(true);
  const [loadingAI, setLoadingAI] = useState(false);
  const [aiError, setAiError] = useState("");

  const fetchStatsAndLots = async () => {
    try {
      setLoadingStats(true);
      
      // Fetch core stat aggregations
      const resStats = await fetch("/api/dashboard/summary", {
        headers: { Authorization: `Bearer ${token}` }
      });
      if (resStats.ok) {
        const data = await resStats.json();
        setStats(data);
      }

      // Fetch active lots for the visual chart
      const resLots = await fetch("/api/inventory/overview", {
        headers: { Authorization: `Bearer ${token}` }
      });
      if (resLots.ok) {
        const lotsData = await resLots.json();
        setLots(lotsData);
      }
    } catch (e) {
      console.error(e);
      triggerToast("Failed to fetch dashboard metrics", "error");
    } finally {
      setLoadingStats(false);
    }
  };

  const fetchRestockForecasts = async () => {
    try {
      setLoadingAI(true);
      setAiError("");
      const res = await fetch("/api/ai/predictive-restocks", {
        headers: { Authorization: `Bearer ${token}` }
      });
      if (!res.ok) {
        const errData = await res.json();
        throw new Error(errData.error || "Model offline");
      }
      const data = await res.json();
      setPredictions(data);
      if (data.length > 0) {
        triggerToast("Replenishment predictions generated by Gemini!", "success");
      } else {
        triggerToast("Pantry is well stacked! No replenishment required.", "success");
      }
    } catch (e: any) {
      console.error(e);
      setAiError(e.message || "Failed to trigger replenishment model. Confirm GEMINI_API_KEY is configured.");
    } finally {
      setLoadingAI(false);
    }
  };

  const addToShoppingList = async (pred: RestockPrediction) => {
    try {
      // 1. Get current shopping list to get main listId
      const listRes = await fetch("/api/list/current", {
        headers: { Authorization: `Bearer ${token}` }
      });
      if (!listRes.ok) throw new Error("Could not find shopping list");
      const listData = await listRes.json();
      const listId = listData.listId;

      // 2. Add entry
      const addRes = await fetch(`/api/list/${listId}/add`, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          Authorization: `Bearer ${token}`
        },
        body: JSON.stringify({
          itemId: pred.itemId,
          customText: pred.itemId ? null : pred.itemName,
          qty: pred.recommendedQty,
          unit: "PIECE", // default placeholder
          source: "replenish"
        })
      });

      if (addRes.ok) {
        triggerToast(`Added ${pred.itemName} (${pred.recommendedQty}) to Grocery List!`, "success");
        fetchStatsAndLots(); // refresh metrics count
        triggerSync(); // tell parent to sync shopping list tab numbers
      } else {
        throw new Error("Add failed");
      }
    } catch (e) {
      triggerToast("Could not place item on shopping list", "error");
    }
  };

  useEffect(() => {
    fetchStatsAndLots();
  }, [token, listsCount]);

  // Aggregate category distributions dynamically for handcrafted visual chart
  const categoryMap: { [key: string]: number } = {};
  lots.forEach(l => {
    const cat = l.category || "Misc";
    categoryMap[cat] = (categoryMap[cat] || 0) + l.remainingQty;
  });

  const chartData = Object.entries(categoryMap).map(([cat, qty]) => ({
    category: cat,
    quantity: Number(qty.toFixed(1))
  })).sort((a, b) => b.quantity - a.quantity);

  const totalChartQty = chartData.reduce((sum, d) => sum + d.quantity, 0) || 1;

  // Custom visual color mapping for category bars
  const getCategoryColor = (cat: string) => {
    const map: { [key: string]: string } = {
      Dairy: "bg-teal-500",
      Produce: "bg-emerald-500",
      Bakery: "bg-amber-500",
      Poultry: "bg-rose-500",
      Meat: "bg-red-500",
      "Pantry Staples": "bg-indigo-500",
      Beverages: "bg-sky-500",
      Snacks: "bg-violet-500",
      Household: "bg-pink-500"
    };
    return map[cat] || "bg-slate-400";
  };

  return (
    <div className="space-y-8 animate-fade-in" id="dashboard-deck">
      {/* Upper Welcome Banner - Minimalist & Modern */}
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-6 bg-white p-6 rounded-2xl border border-slate-200/85 shadow-xs relative overflow-hidden" id="dashboard-welcome-banner">
        <div className="absolute top-0 right-0 w-64 h-64 bg-teal-500/5 rounded-full blur-3xl pointer-events-none" />
        <div className="relative z-10 flex items-center gap-4">
          <span className="p-3 bg-teal-50 text-teal-600 rounded-xl hidden sm:inline-flex shrink-0 border border-teal-150-10">
            <Sparkles className="h-5 w-5 animate-pulse" />
          </span>
          <div>
            <h1 className="text-xl font-extrabold tracking-tight text-slate-900 font-display">
              Household Pantry & Supplies
            </h1>
            <p className="text-xs text-slate-500 mt-1 max-w-xl leading-relaxed">
              Monitor expiry indicators, execute predictive restock models, and balance grocery checklists flawlessly with real-time updates.
            </p>
          </div>
        </div>
        <button
          onClick={fetchStatsAndLots}
          disabled={loadingStats}
          className="relative z-10 flex items-center justify-center gap-2 px-4.5 py-2 border border-slate-200 text-slate-750 bg-white rounded-xl text-xs font-bold hover:bg-slate-50 hover:text-slate-905 hover:border-slate-350 active:scale-95 disabled:opacity-50 transition-all cursor-pointer shadow-2xs"
          id="btn-refresh-dashboard"
        >
          <RefreshCw className={`h-3.5 w-3.5 text-slate-500 ${loadingStats ? "animate-spin" : ""}`} />
          Refresh Stats
        </button>
      </div>

      {/* Main KPI Counter Blocks with matching advanced themes */}
      <div className="grid grid-cols-2 lg:grid-cols-4 gap-4" id="stats-summary-grid">
        {/* KPI 1 - Pantry Items */}
        <div 
          onClick={() => onNavigate("pantry")}
          className="relative overflow-hidden bg-white p-5 rounded-2xl border border-slate-200/80 shadow-xs hover:border-teal-500/45 hover:shadow-md cursor-pointer transition-all duration-300 group hover:-translate-y-0.5 border-l-4 border-l-teal-500"
        >
          <div className="flex justify-between items-start relative z-10">
            <span className="p-2 bg-teal-550/10 text-teal-600 rounded-lg">
              <Package className="h-4.5 w-4.5" />
            </span>
            <ChevronRight className="h-4 w-4 text-slate-400 group-hover:text-teal-600 group-hover:translate-x-0.5 transition-all" />
          </div>
          <div className="mt-4 relative z-10 space-y-1">
            <h3 className="text-[10px] font-bold text-slate-400 uppercase tracking-widest font-mono">Pantry Items</h3>
            {loadingStats ? (
              <div className="space-y-2 py-1">
                <div className="h-7 w-12 bg-slate-100 animate-pulse rounded" />
                <div className="h-3.5 w-20 bg-slate-100 animate-pulse rounded" />
              </div>
            ) : (
              <>
                <p className="text-2xl font-black text-slate-900 font-mono tracking-tight">
                  {stats.totalUniqueItems}
                </p>
                <div className="text-[10px] text-slate-500 flex items-center gap-1 font-bold">
                  <span className="text-teal-600 font-mono">{stats.activeLotsCount}</span> batches
                </div>
              </>
            )}
          </div>
        </div>

        {/* KPI 2 - Expiring Soon */}
        <div 
          onClick={() => onNavigate("pantry")}
          className="relative overflow-hidden bg-white p-5 rounded-2xl border border-slate-200/80 shadow-xs hover:border-rose-500/45 hover:shadow-md cursor-pointer transition-all duration-300 group hover:-translate-y-0.5 border-l-4 border-l-rose-500"
        >
          <div className="flex justify-between items-start relative z-10">
            <span className="p-2 bg-rose-550/10 text-rose-600 rounded-lg">
              <AlertTriangle className="h-4.5 w-4.5" />
            </span>
            <ChevronRight className="h-4 w-4 text-slate-400 group-hover:text-rose-600 group-hover:translate-x-0.5 transition-all" />
          </div>
          <div className="mt-4 relative z-10 space-y-1">
            <h3 className="text-[10px] font-bold text-slate-400 uppercase tracking-widest font-mono">Expiring Soon</h3>
            {loadingStats ? (
              <div className="space-y-2 py-1">
                <div className="h-7 w-12 bg-slate-100 animate-pulse rounded" />
                <div className="h-3.5 w-20 bg-slate-100 animate-pulse rounded" />
              </div>
            ) : (
              <>
                <p className="text-2xl font-black text-slate-900 font-mono tracking-tight">
                  {stats.expiringSoonCount}
                </p>
                <div className="text-[10px] flex items-center gap-1.5 font-bold">
                  {stats.expiredCount > 0 ? (
                    <span className="text-rose-600 font-bold animate-pulse">● {stats.expiredCount} expired</span>
                  ) : (
                    <span className="text-slate-400 font-normal">Next 3 days window</span>
                  )}
                </div>
              </>
            )}
          </div>
        </div>

        {/* KPI 3 - Low Stock Alarms */}
        <div 
          onClick={() => onNavigate("pantry")}
          className="relative overflow-hidden bg-white p-5 rounded-2xl border border-slate-200/80 shadow-xs hover:border-amber-500/45 hover:shadow-md cursor-pointer transition-all duration-300 group hover:-translate-y-0.5 border-l-4 border-l-amber-500"
        >
          <div className="flex justify-between items-start relative z-10">
            <span className="p-2 bg-amber-550/10 text-amber-600 rounded-lg">
              <TrendingDown className="h-4.5 w-4.5" />
            </span>
            <ChevronRight className="h-4 w-4 text-slate-400 group-hover:text-amber-600 group-hover:translate-x-0.5 transition-all" />
          </div>
          <div className="mt-4 relative z-10 space-y-1">
            <h3 className="text-[10px] font-bold text-slate-400 uppercase tracking-widest font-mono">Low Stock</h3>
            {loadingStats ? (
              <div className="space-y-2 py-1">
                <div className="h-7 w-12 bg-slate-100 animate-pulse rounded" />
                <div className="h-3.5 w-20 bg-slate-100 animate-pulse rounded" />
              </div>
            ) : (
              <>
                <p className="text-2xl font-black text-slate-900 font-mono tracking-tight">
                  {stats.lowStockAlarmCount}
                </p>
                <div className="text-[10px] text-slate-400 font-normal">
                  Below safety limits
                </div>
              </>
            )}
          </div>
        </div>

        {/* KPI 4 - Shopping List */}
        <div 
          onClick={() => onNavigate("grocery")}
          className="relative overflow-hidden bg-white p-5 rounded-2xl border border-slate-200/80 shadow-xs hover:border-indigo-500/45 hover:shadow-md cursor-pointer transition-all duration-300 group hover:-translate-y-0.5 border-l-4 border-l-indigo-500"
        >
          <div className="flex justify-between items-start relative z-10">
            <span className="p-2 bg-indigo-550/10 text-indigo-600 rounded-lg">
              <ShoppingCart className="h-4.5 w-4.5" />
            </span>
            <ChevronRight className="h-4 w-4 text-slate-400 group-hover:text-indigo-600 group-hover:translate-x-0.5 transition-all" />
          </div>
          <div className="mt-4 relative z-10 space-y-1">
            <h3 className="text-[10px] font-bold text-slate-400 uppercase tracking-widest font-mono">Shopping List</h3>
            {loadingStats ? (
              <div className="space-y-2 py-1">
                <div className="h-7 w-12 bg-slate-100 animate-pulse rounded" />
                <div className="h-3.5 w-20 bg-slate-100 animate-pulse rounded" />
              </div>
            ) : (
              <>
                <p className="text-2xl font-black text-slate-900 font-mono tracking-tight">
                  {stats.shoppingListItemsCount}
                </p>
                <div className="text-[10px] text-indigo-600 font-bold font-mono">
                  Active checklist items
                </div>
              </>
            )}
          </div>
        </div>
      </div>

      {/* Grid: Charts vs AI Restock Forecasts */}
      <div className="grid grid-cols-1 lg:grid-cols-5 gap-6">
        {/* Left Column: Visual Hand-Crafted Category Chart (2/5 size) */}
        <div className="bg-gradient-to-b from-white to-slate-50/40 p-6 rounded-3xl border border-slate-150/80 shadow-md shadow-slate-100 lg:col-span-2 space-y-6">
          <div>
            <h2 className="text-sm font-bold text-slate-800 uppercase tracking-wider font-mono">Category Stock</h2>
            <p className="text-xs text-slate-400 mt-1">Numerical distribution of active holdings.</p>
          </div>

          {loadingStats ? (
            <div className="flex items-center justify-center py-20">
              <RefreshCw className="h-6 w-6 text-slate-350 animate-spin" />
            </div>
          ) : chartData.length === 0 ? (
            <div className="flex flex-col items-center justify-center p-8 border border-dashed border-slate-100 rounded-xl bg-slate-50/50">
              <Package className="h-8 w-8 text-slate-300" />
              <p className="text-xs text-slate-500 mt-3 font-medium">No inventory active to map.</p>
              <button 
                onClick={() => onNavigate("pantry")}
                className="mt-3 text-xs font-semibold text-teal-600 hover:underline"
              >
                Log items with counts
              </button>
            </div>
          ) : (
            <div className="space-y-5">
              {chartData.map(data => {
                const percentage = Math.max(5, Math.min(100, Math.round((data.quantity / totalChartQty) * 100)));
                return (
                  <div key={data.category} className="space-y-1">
                    <div className="flex justify-between items-center text-xs">
                      <span className="font-medium text-slate-700">{data.category}</span>
                      <span className="text-slate-500 font-mono font-medium">{data.quantity} units ({percentage}%)</span>
                    </div>
                    <div className="h-2 w-full bg-slate-100 rounded-full overflow-hidden">
                      <div 
                        className={`h-full rounded-full transition-all duration-1000 ${getCategoryColor(data.category)}`}
                        style={{ width: `${percentage}%` }}
                      />
                    </div>
                  </div>
                );
              })}
            </div>
          )}
        </div>

        {/* Right Column: AI Replenishment forecasting card */}
        <div className="bg-white p-6 rounded-3xl border border-slate-200/80 shadow-md shadow-slate-100/10 lg:col-span-3 space-y-6 flex flex-col justify-between">
          <div className="space-y-4">
            <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 border-b border-slate-150 pb-4">
              <div className="flex items-center gap-2">
                <span className="p-2 rounded-xl bg-pink-50 text-pink-500 border border-pink-100 animate-pulse">
                  <Sparkles className="h-4.5 w-4.5" />
                </span>
                <div>
                  <h3 className="text-sm font-bold text-slate-800 uppercase tracking-wider font-mono flex items-center gap-1.5">
                    Replenishment Forecasts
                  </h3>
                  <p className="text-xs text-slate-500 mt-1">Gemini models spot stock depletion risk before you run out.</p>
                </div>
              </div>

              <button
                onClick={fetchRestockForecasts}
                disabled={loadingAI}
                className="flex items-center gap-1.5 px-3.5 py-2 bg-slate-900 text-white rounded-xl text-xs font-bold transition-all cursor-pointer shadow-xs hover:bg-slate-800 active:scale-95 disabled:opacity-50 self-start"
              >
                <Sparkles className="h-3 w-3 text-pink-400" />
                {predictions.length > 0 ? "Re-calculate" : "Predict Restocks"}
              </button>
            </div>

            {loadingAI ? (
              <div className="space-y-3.5">
                {[1, 2, 3].map((n) => (
                  <div key={n} className="p-4 border border-slate-150 rounded-xl bg-slate-50/30 flex justify-between items-center animate-pulse">
                    <div className="space-y-2 w-2/3">
                      <div className="h-3.5 bg-slate-200 rounded w-1/3" />
                      <div className="h-3 bg-slate-150 rounded w-3/4" />
                    </div>
                    <div className="h-7 bg-slate-200 rounded w-16" />
                  </div>
                ))}
              </div>
            ) : aiError ? (
              <div className="p-4 border border-rose-100 bg-rose-50/50 rounded-xl text-xs text-rose-600">
                <AlertTriangle className="h-4 w-4 inline mr-1.5" />
                {aiError}
              </div>
            ) : predictions.length === 0 ? (
              <div className="flex flex-col items-center justify-center p-8 border border-dashed border-slate-200/60 rounded-2xl bg-slate-50/50 py-12">
                <Sparkles className="h-8 w-8 text-slate-300" />
                <p className="text-xs text-slate-500 mt-3 font-semibold text-center">
                  Trigger predictive modeling to identify depletion risk.<br />
                  <span className="text-slate-400 font-normal">Calculates matching inventory levels, stock thresholds & consumption metrics.</span>
                </p>
              </div>
            ) : (
              <div className="space-y-3 max-h-[300px] overflow-y-auto pr-1">
                {predictions.map((pred, i) => (
                  <div 
                    key={i} 
                    className="p-4 border border-pink-100/70 hover:border-pink-500/30 rounded-xl bg-white flex items-center justify-between gap-3 hover:shadow-sm hover:shadow-pink-500/5 transition-all group"
                  >
                    <div className="space-y-1">
                      <div className="flex items-center gap-2">
                        <span className="font-bold text-xs text-slate-800">{pred.itemName}</span>
                        <span className={`px-2 py-0.5 rounded text-[9px] font-bold ${
                          pred.confidence > 0.8 
                            ? "bg-rose-500/10 text-rose-600 border border-rose-200/30" 
                            : "bg-amber-500/10 text-amber-600 border border-amber-200/30"
                        }`}>
                          {Math.round(pred.confidence * 100)}% risk
                        </span>
                      </div>
                      <p className="text-[11px] text-slate-400 leading-normal">{pred.reason}</p>
                    </div>

                    <button
                      onClick={() => addToShoppingList(pred)}
                      className="flex items-center gap-1.5 px-3 py-1.5 border border-slate-200 text-slate-600 hover:border-teal-500 hover:text-teal-600 hover:bg-teal-50/40 rounded-lg text-[10px] font-extrabold bg-white transition-all shadow-2xs shrink-0 cursor-pointer active:scale-95"
                    >
                      <ShoppingCart className="h-3 w-3" />
                      Keep ({pred.recommendedQty})
                    </button>
                  </div>
                ))}
              </div>
            )}
          </div>

          <div className="border-t border-slate-100/80 pt-4 mt-4 flex items-center justify-between text-[11px] text-slate-400">
            <div className="flex items-center gap-1">
              <CheckCircle2 className="h-3.5 w-3.5 text-teal-500" />
              <span>Offline sync active</span>
            </div>
            <span>Power prediction models securely</span>
          </div>
        </div>
      </div>
    </div>
  );
}
